services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama

  app:
    build: .
    depends_on:
      - ollama
    volumes:
      - ./app:/app/app
      - ./productos.json:/app/productos.json
      - app_chroma_data:/app/chroma_data  
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:192.168.100.12"

volumes:
  app_chroma_data:
  ollama_data: